export type HomepageCmsMap = Record<string, string>;

export const HOMEPAGE_CMS_DEFAULTS: HomepageCmsMap = {
  "sections.hero.enabled": "true",
  "hero.slides_json": "",
  "hero.autoplay_enabled": "true",
  "hero.autoplay_interval": "6",
  "hero.badge_text": "AI-Powered Listing Optimization",
  "hero.heading_line1": "Optimize Listings. Increase Sales.",
  "hero.heading_highlight": "Grow Faster.",
  "hero.subheading": "Audit listings, create stunning content, manage ads and dominate every marketplace.",
  "hero.cta_primary_text": "Get Started Free",
  "hero.cta_primary_url": "/sign-up",
  "hero.cta_secondary_text": "See How It Works",
  "hero.cta_secondary_url": "/features",
  "hero.stat1_value": "50M+",
  "hero.stat1_label": "Listings Analyzed",
  "hero.stat2_value": "15M+",
  "hero.stat2_label": "Assets Generated",
  "hero.stat3_value": "97%",
  "hero.stat3_label": "Optimization Score",
  "hero.stat4_value": "5000+",
  "hero.stat4_label": "Brands Trust Us",

  "sections.features.enabled": "true",
  "features.eyebrow": "What you can do",
  "features.heading": "Everything you need to win on marketplaces",
  "features.subheading": "Powerful tools and insights to optimize listings, create stunning content, and scale your business.",
  "features.footer_text": "All tools. One platform. Save time, reduce costs, and grow your business faster.",
  "features.item1_title": "Audit Listings",
  "features.item1_desc": "Advanced AI audits to find issues, improve rankings, and boost performance.",
  "features.item1_href": "/audit-listings",
  "features.item1_bullet1": "SEO & Content Analysis",
  "features.item1_bullet2": "Issue Detection",
  "features.item1_bullet3": "Actionable Recommendations",
  "features.item1_image": "",
  "features.item2_title": "Build Your Brand",
  "features.item2_desc": "Craft a powerful brand identity that stands out and builds customer trust.",
  "features.item2_href": "/audits/new",
  "features.item2_bullet1": "Brand Strategy",
  "features.item2_bullet2": "Logo & Identity",
  "features.item2_bullet3": "Brand Guidelines",
  "features.item2_image": "",
  "features.item3_title": "Create Graphics",
  "features.item3_desc": "Stunning product images and infographics that convert browsers into buyers.",
  "features.item3_href": "/projects",
  "features.item3_bullet1": "AI Image Generation",
  "features.item3_bullet2": "Infographics",
  "features.item3_bullet3": "Lifestyle Images",
  "features.item3_image": "",
  "features.item4_title": "Create Videos",
  "features.item4_desc": "Engaging product videos that showcase features and drive more sales.",
  "features.item4_href": "/videos",
  "features.item4_bullet1": "Product Videos",
  "features.item4_bullet2": "Feature Highlights",
  "features.item4_bullet3": "Social Media Ready",
  "features.item4_image": "",
  "features.item5_title": "Manage Ads",
  "features.item5_desc": "Optimize and scale your ad campaigns to maximize ROAS and sales.",
  "features.item5_href": "/ads",
  "features.item5_bullet1": "Campaign Management",
  "features.item5_bullet2": "Performance Tracking",
  "features.item5_bullet3": "Keyword Optimization",
  "features.item5_image": "",

  "sections.portfolio.enabled": "true",
  "portfolio.heading": "Real results we've created for brands like yours",
  "portfolio.subheading": "Premium listing graphics, A+ content, and lifestyle assets created with SellerLens AI.",
  "portfolio.cta_text": "View More Works",
  "portfolio.cta_url": "/features",
  "portfolio.item1_image": "/portfolio/product-hydration-kit.png",
  "portfolio.item1_title": "Product Images",
  "portfolio.item1_brand": "Home & Kitchen",
  "portfolio.item1_fit": "cover",
  "portfolio.item2_image": "/portfolio/aplus-timewear-hero.png",
  "portfolio.item2_title": "A+ Content",
  "portfolio.item2_brand": "TIMEWEAR",
  "portfolio.item2_fit": "contain",
  "portfolio.item3_image": "/portfolio/lifestyle-timewear.png",
  "portfolio.item3_title": "Lifestyle Images",
  "portfolio.item3_brand": "TIMEWEAR",
  "portfolio.item3_badge": "NEW",
  "portfolio.item3_fit": "contain",
  "portfolio.item4_image": "/portfolio/infographic-water-bottle.png",
  "portfolio.item4_title": "Infographic",
  "portfolio.item4_brand": "Home & Kitchen",
  "portfolio.item4_fit": "contain",
  "portfolio.item5_image": "/portfolio/size-chart-timewear.png",
  "portfolio.item5_title": "Size Chart",
  "portfolio.item5_brand": "TIMEWEAR",
  "portfolio.item5_fit": "contain",
  "portfolio.item6_image": "/portfolio/portfolio-aplus-product-hero.jpg",
  "portfolio.item6_title": "A+ Hero Banner",
  "portfolio.item6_brand": "Premium Brands",
  "portfolio.item6_fit": "cover",
  "portfolio.item7_image": "/portfolio/portfolio-infographic-fitness.jpg",
  "portfolio.item7_title": "Feature Highlights",
  "portfolio.item7_brand": "Sports & Fitness",
  "portfolio.item7_fit": "cover",
  "portfolio.item8_image": "/portfolio/portfolio-brand-story-pet.jpg",
  "portfolio.item8_title": "Brand Story Module",
  "portfolio.item8_brand": "Pet Essentials",
  "portfolio.item8_fit": "cover",

  "sections.workflow.enabled": "true",
  "workflow.heading": "From Upload to Publish in 6 Simple Steps",
  "workflow.step1_label": "Upload",
  "workflow.step2_label": "Analyze",
  "workflow.step3_label": "Optimize",
  "workflow.step4_label": "Generate Assets",
  "workflow.step5_label": "Export",
  "workflow.step6_label": "Publish",
  "workflow.before_label": "Before",
  "workflow.before_score": "62",
  "workflow.before_image": "https://images.unsplash.com/photo-1585386959984-a4155224a1ad?w=400&h=200&fit=crop&q=80",
  "workflow.after_label": "After",
  "workflow.after_badge": "AI Optimized",
  "workflow.after_score": "96",
  "workflow.after_image": "https://images.unsplash.com/photo-1608571423902-eed4a5ad8108?w=400&h=200&fit=crop&q=80",
  "workflow.metrics_heading": "Better Listings. Better Results.",
  "workflow.metric1_value": "+34%",
  "workflow.metric1_label": "Click Through Rate",
  "workflow.metric2_value": "+27%",
  "workflow.metric2_label": "Conversion Rate",
  "workflow.metric3_value": "+18%",
  "workflow.metric3_label": "Organic Rank",
  "workflow.metric4_value": "+40%",
  "workflow.metric4_label": "Sales Growth",

  "sections.tutorials.enabled": "true",
  "tutorials.heading": "Learn how to get the most out of SellerLens",
  "tutorials.cta_text": "View All Tutorials",
  "tutorials.cta_url": "/tutorials",
  "tutorials_page.heading": "Help Center & Tutorials",
  "tutorials_page.subheading": "Learn how to get the most out of SellerLens with step-by-step guides, video tutorials, and best practices.",
  "tutorials_page.search_placeholder": "Search tutorials...",
  "tutorials_page.cta_heading": "Still need help?",
  "tutorials_page.cta_subheading": "Our support team is here to help you get the most out of SellerLens.",
  "tutorials_page.cta_primary_text": "Contact Support",
  "tutorials_page.cta_primary_url": "/contact",
  "tutorials_page.cta_secondary_text": "Browse Help Center",
  "tutorials_page.cta_secondary_url": "/help",
  "tutorials.item1_title": "Getting Started",
  "tutorials.item1_duration": "5:32",
  "tutorials.item1_image": "https://images.unsplash.com/photo-1460925895917-afdab827c52f?w=400&h=240&fit=crop&q=80",
  "tutorials.item1_description": "Learn how to paste any Amazon product URL and get a complete AI-powered audit in seconds.",
  "tutorials.item1_category": "getting-started",
  "tutorials.item1_steps": "4",
  "tutorials.item2_title": "Audit Your Listing",
  "tutorials.item2_duration": "7:15",
  "tutorials.item2_image": "https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=400&h=240&fit=crop&q=80",
  "tutorials.item2_description": "Break down the scoring categories and what each means for your listing performance.",
  "tutorials.item2_category": "analytics",
  "tutorials.item2_steps": "6",
  "tutorials.item3_title": "Optimize Content",
  "tutorials.item3_duration": "6:48",
  "tutorials.item3_image": "https://images.unsplash.com/photo-1432888622747-4eb9a8efeb07?w=400&h=240&fit=crop&q=80",
  "tutorials.item3_description": "Step-by-step guide to rewriting product titles and bullets that rank higher and convert better.",
  "tutorials.item3_category": "optimization",
  "tutorials.item3_steps": "5",
  "tutorials.item4_title": "Create A+ Content",
  "tutorials.item4_duration": "8:20",
  "tutorials.item4_image": "https://images.unsplash.com/photo-1516321318423-f06f85e504b3?w=400&h=240&fit=crop&q=80",
  "tutorials.item4_description": "How our AI evaluates your product images and what you can do to improve your image score.",
  "tutorials.item4_category": "images",
  "tutorials.item4_steps": "4",
  "tutorials.item5_title": "Manage Ads",
  "tutorials.item5_duration": "9:05",
  "tutorials.item5_image": "https://images.unsplash.com/photo-1556761175-b413da4baf72?w=400&h=240&fit=crop&q=80",
  "tutorials.item5_description": "Optimize and scale your ad campaigns to maximize ROAS and sales.",
  "tutorials.item5_category": "optimization",
  "tutorials.item5_steps": "5",

  "sections.pricing.enabled": "true",
  "pricing.eyebrow": "Simple, Transparent Pricing",
  "pricing.heading": "Choose the plan that fits your growth",
  "pricing.footer_text": "Need a custom plan?",
  "pricing.footer_link_text": "Contact us →",
  "pricing.footer_link_url": "/contact",

  "sections.faq.enabled": "true",
  "faq.heading": "Frequently Asked Questions",
  "faq.q1": "What is SellerLens?",
  "faq.a1": "SellerLens is an AI-powered platform that helps Amazon and marketplace sellers audit listings, generate content, and grow sales.",
  "faq.q2": "How do credits work?",
  "faq.a2": "Credits are used for AI audits, content generation, and image creation. Each plan includes monthly credits that roll over.",
  "faq.q3": "Can I try it for free?",
  "faq.a3": "Yes! Sign up for a free account and get starter credits to try our core features.",
  "faq.q4": "Which marketplaces do you support?",
  "faq.a4": "We support Amazon, Shopify, Walmart, eBay, and most major e-commerce platforms.",
  "faq.q5": "How do I get support?",
  "faq.a5": "Reach out via our Contact page or Help Center — our team typically responds within 24 hours.",

  "sections.cta.enabled": "true",
  "cta.heading": "Ready to build better listings and grow your business?",
  "cta.subheading": "Join thousands of brands already winning with AI.",
  "cta.primary_text": "Get Started Free",
  "cta.primary_url": "/sign-up",
  "cta.secondary_text": "See How It Works",
  "cta.secondary_url": "/features",

  "sections.social.enabled": "true",
  "social.trusted_heading": "Trusted by leading brands",

  "nav.sign_in_text": "Sign In",
  "nav.sign_in_url": "/sign-in",
  "nav.cta_text": "Get Started Free",
  "nav.cta_url": "/sign-up",

  "seo.title": "AI-Powered Listing Optimization",
  "seo.description": "Audit listings, create stunning content, manage ads and dominate every marketplace.",

  "footer.tagline": "AI-powered listing optimization for sellers who want to rank higher and convert better.",
  "footer.copyright": "All rights reserved.",
  "footer.social_twitter": "https://twitter.com",
  "footer.social_linkedin": "https://linkedin.com",
  "footer.social_youtube": "https://youtube.com",
  "footer.social_facebook": "https://facebook.com",
};

export function mergeHomepageCms(data: HomepageCmsMap): HomepageCmsMap {
  return { ...HOMEPAGE_CMS_DEFAULTS, ...data };
}

export function cmsText(cms: HomepageCmsMap, key: string): string {
  const value = cms[key];
  if (value === undefined || value === "") {
    return HOMEPAGE_CMS_DEFAULTS[key] ?? "";
  }
  return value;
}

export function cmsEnabled(cms: HomepageCmsMap, section: string): boolean {
  const value = cmsText(cms, `sections.${section}.enabled`);
  return value !== "false" && value !== "0";
}

export function resolveCmsAssetUrl(path: string, basePath: string): string {
  if (!path) return "";
  if (path.startsWith("http://") || path.startsWith("https://") || path.startsWith("data:")) {
    return path;
  }
  const normalized = path.startsWith("/") ? path : `/${path}`;
  if (normalized.startsWith(basePath) || basePath === "") {
    return normalized;
  }
  return `${basePath}${normalized}`;
}
